name: Build Mod Menu
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Esta línea instala Gradle automáticamente si el tuyo falla
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Ejecutamos la compilación usando el Gradle del sistema
      - name: Build with Gradle
        run: gradle assembleDebug

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MiModMenu
          path: app/build/outputs/apk/debug/
